routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::any('/admin', 'Auth\LoginController@login')->name('admin-login');
Route::get('admin-logout', [ 'as' => 'admin-logout', 'uses' =>'Auth\LoginController@logout']);
Route::post('userregistration',  [ 'as' => 'userregistration', 'uses' =>'Auth\AuthController@storeUser']);

Route::get('/', function () {
	    return view('cerexam/index');
	});
	

Route::post('user-login', [ 'as' => 'user-login', 'uses' =>'Auth\AuthController@authenticate']);

Auth::routes();
Route::prefix('admin')->group(function () {
Route::group(array('middleware' => 'auth'), function() {
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    Route::resource('users', 'UserController');
	Route::post('users/update-project/{id}', [ 'as' => 'updateproject-details', 'uses' =>'UserController@updateProjectDetails']);
});
});
Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    return back()->with('message', 'Verification link sent!');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

Auth::routes(['verify' => true]);
Route::prefix('user')->group(function () {
	Route::group(array('middleware' => 'auth'), function() {
		Route::get('myprofile', [ 'as' => 'myprofile', 'uses' =>'User\UserController@getProfileDetails']);
		Route::get('editdetails', [ 'as' => 'editdetails', 'uses' =>'User\UserController@geteditDetailsPage']);
		Route::post('updateprofile', [ 'as' => 'updateprofile', 'uses' =>'User\UserController@updateProfileDetails']);
		Route::get('my-uploads', [ 'as' => 'my-uploads', 'uses' =>'User\UserController@getUploadDetails']);
		Route::post('updateuploads', [ 'as' => 'updateuploads', 'uses' =>'User\UserController@updateUploadDetails']);
		Route::get('my-document', [ 'as' => 'my-document', 'uses' =>'User\UserController@getMyDocuments']);
		Route::post('updatedocuments', [ 'as' => 'updatedocuments', 'uses' =>'User\UserController@updateDocuments']);
		Route::get('change-password', function () {
		    return view('auth/changepassword');
		});
		Route::post('updatepassword', [ 'as' => 'updatepassword', 'uses' =>'Auth\AuthController@changePassword']);
		Route::get('logout', 'Auth\AuthController@logout')->name('logout');
	});
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'firstname','lastname', 'email', 'contact_no','password','dob','address','city' ,'state' ,'pincode' ,'education' ,'school_clg' ,'profile_pic' ,'startup','interested_to_register','company_name'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Auth;
use Illuminate\Support\Facades\View;
use App\User;
use App\Upload;
use Session;
use Storage;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
    }
    public function getProfileDetails()
    { 
        $users = Auth::user();
        $uploads = Upload::where('user_id', $users->id)->first();
        return view('auth.profile', ['user' => $users,'uploads' => $uploads]);
    }
    public function geteditDetailsPage()
    {
         $users = Auth::user();
        $uploads = Upload::where('user_id', $users->id)->first();
        return view('auth.editprofile', ['user' => $users,'uploads' => $uploads]);
    }
    public function updateProfileDetails(Request $request)
    {
    	$request->validate([
	            'firstname' => 'required|string|max:255',
	            'lastname' => 'required|string|max:255',
	            'contact_no' => 'required|integer',
                'resume' => 'required||mimes:docx,pdf'
	        ]);
    	try{
            $profileName = isset($request->hidden_profile_pic) ? $request->hidden_profile_pic : $request->profile_pic;
    		$userId = Auth::id();
    		$user = User::findOrFail($userId);
            /** Resume */
                if(request()->resume != null){
                    $resume = $user->id.'_resume'.rand(0,1000).'.'.request()->resume->getClientOriginalExtension();
                    // $request->resume->storeAs('resume',$resume);   
                    Storage::disk('s3')->put($resume, file_get_contents($request->resume));
                    $user->resume = $resume;
                }
            if(isset($request->update_profile_pic) && $request->update_profile_pic != ""){
                $profileName = $user->id.'_avatar'.time().'.'.request()->update_profile_pic->getClientOriginalExtension();
                // $request->update_profile_pic->storeAs('avatars',$profileName);
                Storage::disk('s3')->put($profileName, file_get_contents($request->update_profile_pic));
            }elseif(!isset($request->hidden_profile_pic) && $request->profile_pic){
               
                // $this->validate($request,[
                //     'profile_pic' =>  'mimes:png',
                // ]);
                $profileName = $user->id.'_avatar'.time().'.'.request()->profile_pic->getClientOriginalExtension();
                // $request->profile_pic->storeAs('avatars',$profileName);
                Storage::disk('s3')->put($profileName, file_get_contents($request->profile_pic));
            }
           // if(isset($request->interested_to_register)){
           //      $interested = 1;
           //  }else{
           //      $interested = NULL;
           //  }
           //  if(isset($request->startup)){
           //      $startup = 1;
           //  }else{
           //      $startup = NULL;
           //  }
    		 $user->fill([
	            'contact_no' => $request->contact_no,
                'dob' => $request->dob,
                'address' => $request->address,
                'city' => $request->city,
                'state' => $request->state,
                'pincode' => $request->pincode,
                'education' => $request->education,
                'school_clg' => $request->school_clg,
                'profile_pic' => $profileName,
                'startup' => $request->startup,
                'interested_to_register' => $request->interested_to_register,
                'company_name' => $request->company_name
	        ]);
	        // Save user to database
            Session::flash('success', 'Profile updated successfully.');// 
	        $user->save();
            return redirect('user/myprofile');
	    }catch(\Exception $e){
            Session::flash('error', $e->getMessage());
    		 return redirect('user/myprofile');
    	}
    }

    public function getUploadDetails()
    {
        $userId = Auth::id();
        $uploads = Upload::where('user_id', $userId)->first();
        return view('cerexam.my-uploads', ['data' => $uploads]);
        
    }

    public function updateUploadDetails(Request $request)
    { 
        $request->validate([
                'name' => 'required|string|max:255',
                'devkit' => 'required|string|max:255',
            ]);
        try{
            $userId = Auth::id();
            $uploads = Upload::where('user_id', $userId)->first();

            if($uploads){
                $uploads->fill([
                    'user_id' => $userId,
                    'name' => $request->name,
                    'devkit' => $request->devkit,
                    'other_accessories_used' => $request->other_accessories_used,
                    'usecase' => $request->usecase,
                    'otherdetails' => $request->otherdetails
                ]);
            }else{
                $uploads = new Upload;
                $uploads->user_id = $userId;
                $uploads->name = $request->name;
                $uploads->devkit = $request->devkit;
                $uploads->other_accessories_used = $request->other_accessories_used;
                $uploads->usecase = $request->usecase;
                $uploads->otherdetails = $request->otherdetails;
            }
            // Save uploads to database
            $uploads->save();
            Session::flash('success', 'Details updated successfully.');
            return redirect('user/my-document');
        }catch(\Exception $e){
            Session::flash('error', $e->getMessage());
            return redirect('user/my-uploads');
        }
    }
    /**
     * Get My Documents
     */
    public function getMyDocuments(Request $request){
        $userId = Auth::id();
        $uploads = Upload::where('user_id', $userId)->first();
        return view('cerexam.document', ['data' => $uploads]);
    }
    /**
     * Update Documents
     */
    public function updateDocuments(Request $request){
        $userId = Auth::id();
        $uploads = Upload::where('user_id', $userId)->first();
        if($uploads->document_file != null){
            $request->validate([
            'document_file' => 'mimes:docx,pdf',
            'picture_1' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            'picture_2' => 'image|mimes:jpeg,png,jpg|max:2048',
            'picture_3' => 'image|mimes:jpeg,png,jpg|max:2048',
            'video' => 'required|mimes:mp4,mov|max:20000'
        ]);
        }else{
            $request->validate([
                'document_file' => 'required|mimes:docx,pdf',
                'picture_1' => 'required|image|mimes:jpeg,png,jpg|max:2048',
                'picture_2' => 'image|mimes:jpeg,png,jpg|max:2048',
                'picture_3' => 'image|mimes:jpeg,png,jpg|max:2048',
                'video' => 'required|mimes:mp4,mov|max:20000'
            ]);
         }
        try{
            $data = $request->all();
            unset($data['_token']);
            if(!empty($data) && $uploads){
                /** Document File */
                if(request()->document_file != null){
                    $documentFile = $uploads->id.'_document'.rand(0,1000).'.'.request()->document_file->getClientOriginalExtension();
                    Storage::disk('s3')->put($documentFile, file_get_contents($request->document_file));
                    // $request->document_file->storeAs('documents',$documentFile);   
                    $uploads->document_file = $documentFile;
                }
                /** Picture 1 */
                if(request()->picture_1 != null){
                    $picture_1 = $uploads->id.'_document'.rand(0,1000).'.'.request()->picture_1->getClientOriginalExtension();
                    Storage::disk('s3')->put($picture_1, file_get_contents($request->picture_1));
                    // $request->picture_1->storeAs('documents',$picture_1);   
                    $uploads->picture_1 = $picture_1;
                }
                /** Picture 2 */
                if(request()->picture_2 != null){
                    $picture_2 = $uploads->id.'_document'.rand(0,1000).'.'.request()->picture_2->getClientOriginalExtension();
                    Storage::disk('s3')->put($picture_2, file_get_contents($request->picture_2));
                    // $request->picture_2->storeAs('documents',$picture_2);   
                    $uploads->picture_2 = $picture_2;
                }
                /** Picture 3 */
                if(request()->picture_3 != null){
                    $picture_3 = $uploads->id.'_document'.rand(0,1000).'.'.request()->picture_3->getClientOriginalExtension();
                    Storage::disk('s3')->put($picture_3, file_get_contents($request->picture_3));
                    // $request->picture_3->storeAs('documents',$picture_3);   
                    $uploads->picture_3 = $picture_3;
                }
                /** Video */
                if(request()->video != null){
                    $video = $uploads->id.'_document'.rand(0,1000).'.'.request()->video->getClientOriginalExtension();
                    Storage::disk('s3')->put($video, file_get_contents($request->video));
                    // $request->video->storeAs('documents',$video);   
                    $uploads->video = $video;
                }
                $uploads->save();
                Session::flash('success', 'Documents updated successfully.');
            }
            return redirect('user/editdetails');
        }catch(\Exception $e){
            Session::flash('error', $e->getMessage());
            return redirect('user/editdetails');
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Upload;
use Auth;
use Session;
use Storage;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::where('id','!=',Auth::id())->get();
        return view('user.list', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $users = User::where('id','=',$id)->first();
        $uploads = Upload::where('user_id', $id)->first();
        return view('user.view', ['user' => $users,'uploads' => $uploads]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'firstname' => 'required',
            'lastname' => 'required',
            'contact_no' => 'required'
        ]);
        if($request->interested_to_register == '1' && isset($request->resumefile)){
            $request->validate([
                'resume' => 'required||mimes:docx,pdf'
            ]);
        }
        try{
            $user = User::where('id',$id)->first();

            if(request()->resume != null){
                $resume = $user->id.'_resume'.rand(0,1000).'.'.request()->resume->getClientOriginalExtension();
                // $request->resume->storeAs('resume',$resume);   
                Storage::disk('s3')->put($resume, file_get_contents($request->resume));
                $user->resume = $resume;
            }
            $user->firstname = $request->firstname;
            $user->lastname = $request->lastname;
            $user->contact_no = $request->contact_no;
            $user->city = $request->city;
            $user->state = $request->state;
            $user->pincode = $request->pincode;
            $user->address = $request->address;
            $user->school_clg = $request->school_clg;
            $user->company_name = $request->company_name;
            $user->startup = $request->startup;
            $user->interested_to_register = $request->interested_to_register;
            $user->updated_at = now();
            $user->save();
            Session::flash('success', 'User details updated successfully.');
            return redirect()->back();
        }catch(\Exception $e){
            Session::flash('error', $e->getMessage());
            return redirect()->back()->with('error',$e->getMessage());
        }
    }
    /**
     * Update Project Details
     */
    public function updateProjectDetails(Request $request, $id){
        $upload = Upload::where('user_id',$id)->first();
        if($upload != null){
            $upload->name = $request->project_name;
            $upload->devkit = $request->devkit;
            $upload->other_accessories_used = $request->other_accessories_used;
            $upload->usecase = $request->usecase;
            $upload->otherdetails = $request->otherdetails;
            $upload->save();
        }
        Session::flash('success', 'Project details updated successfully.');
        return redirect()->back();
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete($id);
        Session::flash('success', 'Record has been deleted successfully!');
        return response()->json([
            'success' => 'Record has been deleted successfully!'
        ]);
    }
}

resources/views/user/list.blade.php
@extends('layouts.main')
@section('content')
@include('layouts.message')
<script src="{{ asset('/public/js/jquery.dataTables.min.js') }}"></script>
<script
    src="{{ asset('/public/js/dataTables.bootstrap.min.js') }}"></script>
<link rel="stylesheet"
    href="{{ asset('/public/css/dataTables.bootstrap.min.css') }}">

    <!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>Users </h1>
        </div>
      </div>
    </div><!-- /.container-fluid -->
  </section>


  <section class="content">
    @include('layouts.message')
  <div class="container-fluid">
    <div class="row">
      <div class="col-12 col-sm-12">
        <div class="card-body">
            <table class="table table-bordered" id="table">
                <thead>
                    <tr>
                        <th class="text-center">#</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Email</th>
                        <th class="text-center">Contact</th>
                        <th class="text-center">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id}}</td>
                        <td>{{ $user->firstname ." ". $user->lastname}}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->contact_no }}</td>
                        <td><a class="btn btn-success" href="{{ url('admin/users/'.$user->id.'/edit') }}">Edit</a>
                        <button class="deleteUser btn btn-primary" data-id="{{ $user->id }}" data-token="{{ csrf_token() }}" >Delete</button></td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

      </div>
    </div>
  </div>
  </section>

@endsection

resources/views/user/view.blade.php
@extends('layouts.main')
@section('content')
@include('layouts.message')
<style>
	.document-image{
		max-width: 300px;
			border-radius: 7px;
			height: 250px;
			width: 3000px;
		}
</style>
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1></h1>
        </div>
        
      </div>
    </div><!-- /.container-fluid -->
  </section>
  <section class="content">
	  <div class="container-fluid">
		  <div class="row">
			<div class="col-md-12">
				<!-- general form elements -->
				<div class="card card-primary">
				  <div class="card-header">
					<h3 class="card-title">Profile Information</h3>
				  </div>
				  <!-- /.card-header -->
				  <!-- form start -->
				  <form action="{{route('users.update',[$user->id])}}" method="POST">
					@method('PUT')
					@csrf
					<div class="card-body">
						<div class="row">
							@if($user->profile_pic != null)
							<div class="col-md-2 text-center">
								<img class="profile-user-img img-fluid img-circle" src="{{ asset('storage/app/avatars/'.$user->profile_pic) }}" alt="User profile picture">
							</div>
							@endif
							<div class="col-md-3">
								<div class="form-group">
									<label>First Name <span class="text-danger">*</span></label>
									<input type="text" name="firstname" class="form-control" placeholder="Enter first name" value="{{$user->firstname}}">
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label>Last Name <span class="text-danger">*</span></label>
									<input type="text" name="lastname" class="form-control" placeholder="Enter last name" value="{{$user->lastname}}">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label>Email <span class="text-danger">*</span></label>
									<input type="email" name="email" class="form-control" placeholder="Enter email" value="{{$user->email}}" readonly>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label>Contact No <span class="text-danger">*</span></label>
									<input type="text" name="contact_no" class="form-control" placeholder="Enter contact number" value="{{$user->contact_no}}">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label>City</label>
									<input type="text" name="city" class="form-control" placeholder="Enter city name" value="{{$user->city}}">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label>State</label>
									<input type="text" name="state" class="form-control" placeholder="Enter state name" value="{{$user->state}}">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label>Pincode</label>
									<input type="text" name="pincode" class="form-control" placeholder="Enter pincode" value="{{$user->pincode}}">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label>Education</label>
									<input type="text" name="education" class="form-control" placeholder="Enter education" value="{{$user->education}}">
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label>School/College Name</label>
									<input type="text" name="school_clg" class="form-control" placeholder="Enter school/college name" value="{{$user->school_clg}}">
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-2">
								<div class="form-group">
									<div class="form-check">
									  <input class="form-check-input" name="is_startup" type="checkbox" {{($user->startup == 1) ? 'checked' : ''}}>
									  <label class="form-check-label">Interested In Startup?</label>
									</div>
								  </div>
							</div>
							<div class="col-md-2">
								<div class="form-group">
									<div class="form-check">
									  <input class="form-check-input" name="interested_to_register" type="checkbox" {{($user->interested_to_register == 1) ? 'checked' : ''}}>
									  <label class="form-check-label">Interested to Register?</label>
									</div>
								  </div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label>Address</label>
									<textarea name="address" class="form-control">{{$user->address}}</textarea>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label>Company Name</label>
									<input type="text" name="company_name" class="form-control" value="{{$user->company_name}}" />
								</div>
							</div>
						</div>
					</div>
					<!-- /.card-body -->
	
					<div class="card-footer">
					  <button type="submit" class="btn btn-primary">Update</button>
					  <a href="{{route('users.index')}}" class="btn btn-secondary">Cancel</a>
					</div>
				  </form>
				</div>
				<!-- /.card -->
	
			  </div>
		  </div>
		  <div class="row">
			<div class="col-md-12">
				<!-- general form elements -->
				<div class="card card-primary">
				  <div class="card-header">
					<h3 class="card-title">Project Details</h3>
				  </div>
				  <!-- /.card-header -->
				  <!-- form start -->
				  <form action="{{route('updateproject-details',[$user->id])}}" method="POST">
					@csrf
					<div class="card-body">
						<div class="row">
							<div class="col-md-3">
								<div class="form-group">
									<label>Name </label>
									<input type="text" name="project_name" class="form-control" placeholder="Enter project name" value="{{ isset($uploads->name) ? $uploads->name : ''}}">
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label>NVIDIA Jetson Dev kit</label>
									<select name="devkit" class="form-control">
										<option value="1" {{ isset($uploads->devkit) && $uploads->devkit == 1 ? 'selected' : '' }}>Nvidia Jetson nano 2Gb developer kit</option>
										<option value="2" {{ isset($uploads->devkit) && $uploads->devkit == 2 ? 'selected' : '' }}>Nvidia Jetson nano Developer kit - B01</option>
										<option value="3" {{ isset($uploads->devkit) && $uploads->devkit == 3 ? 'selected' : '' }}>Nvidia Jetson nano Developer kit - B01</option>
										<option value="4" {{ isset($uploads->devkit) && $uploads->devkit == 4 ? 'selected' : '' }}>Nvidia Jetson nano Developer kit - B01</option>
									</select>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label>Other Accessories used</label>
									<textarea name="other_accessories_used" class="form-control">{{isset($uploads->other_accessories_used) ? $uploads->other_accessories_used : ''}}</textarea>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label>Application/Use case</label>
									<textarea name="usecase" class="form-control">{{isset($uploads->usecase) ? $uploads->usecase : ''}}</textarea>
								</div>
							</div>
							<div class="col-md-4">
								<div class="form-group">
									<label>Other details/ Reference</label>
									<textarea name="otherdetails" class="form-control">{{isset($uploads->otherdetails) ? $uploads->otherdetails : ''}}</textarea>
								</div>
							</div>
						</div>
					</div>
					<!-- /.card-body -->
	
					<div class="card-footer">
					  <button type="submit" class="btn btn-primary">Update</button>
					  <a href="{{route('users.index')}}" class="btn btn-secondary">Cancel</a>
					</div>
				  </form>
				</div>
				<!-- /.card -->
	
			  </div>
		  </div>
		  <div class="row">
			<div class="col-md-12">
				<!-- general form elements -->
				<div class="card card-primary">
				  <div class="card-header">
					<h3 class="card-title">Documents</h3>
				  </div>
					<div class="card-body">
						<div class="row">
							<div class="col-md-1">
								<div class="form-group">
									<label>Document File </label>
									<div>
										@if(isset($uploads->document_file))
										<a href="{{'https://nvidia-media.s3.us-east-2.amazonaws.com/'.$uploads->document_file}}" target="_blank">Document File</a>
										@endif
									</div>
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label>Picture 1</label>
									<div>
										@if(isset($uploads->picture_1))
										<a href="{{'https://nvidia-media.s3.us-east-2.amazonaws.com/'.$uploads->picture_1}}" target="_blank">
											<img src="{{'https://nvidia-media.s3.us-east-2.amazonaws.com/'.$uploads->picture_1}}" alt="Image not uploaded" class="document-image">
										</a>
										@endif
									</div>
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label>Picture 2</label>
									<div>
										@if(isset($uploads->picture_2))
										<a href="{{'https://nvidia-media.s3.us-east-2.amazonaws.com/'.$uploads->picture_2}}" target="_blank">
											<img src="{{'https://nvidia-media.s3.us-east-2.amazonaws.com/'.$uploads->picture_2}}" alt="Image not uploaded" class="document-image">
										</a>
										@endif
									</div>
								</div>
							</div>
							<div class="col-md-3">
								<div class="form-group">
									<label>Picture 3</label>
									<div>
										@if(isset($uploads->picture_3))
										<a href="{{'https://nvidia-media.s3.us-east-2.amazonaws.com/'.$uploads->picture_3}}" target="_blank">
											<img src="{{'https://nvidia-media.s3.us-east-2.amazonaws.com/'.$uploads->picture_3}}" alt="Image not uploaded" class="document-image">
										</a>
										@endif
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-md-1"></div>
							<div class="col-md-4">
								<div class="form-group">
									<label>Video</label>
									<div>
										@if(isset($uploads->video) && $uploads->video != "")
										<iframe src="{{'https://nvidia-media.s3.us-east-2.amazonaws.com/'.$uploads->video}}" frameborder="0"></iframe>
										@else
										<span>No Video Uploaded</span>
										@endif
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- /.card -->
	
			  </div>
		  </div>
	  </div>
  </section>

</form>
@endsection